"""
Write WCNTSegNET batch summary results back to the images table.

This script:
1. Loads a batch `summary.json` generated by `generate_zzy_cntsegnet_preview.py`
2. Backs up existing database values for the targeted image ids
3. Overwrites the formal image feature columns with WCNTSegNET results

The target database schema only has one formal feature slot per image, so this
script writes WCNTSegNET into the main `images` feature columns.
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any


DEFAULT_DB_PATH = Path(r"D:\CNTDATA\CNTA_ML_Project\database\cnta_experiments.sqlite")
DEFAULT_SUMMARY_PATH = Path(
    r"D:\CNTDATA\CNTA_ML_Project\reports\zzy_wcntsegnet_full_batch_20260324\summary.json"
)


BACKUP_COLUMNS = [
    "id",
    "sample_id",
    "file_path",
    "diameter",
    "density",
    "alignment",
    "curvature",
    "processed",
    "tortuosity",
    "diameter_mean",
    "diameter_std",
    "diameter_min",
    "diameter_max",
    "diameter_p25",
    "diameter_p50",
    "diameter_p75",
    "diameter_distribution",
    "waviness_ratio",
    "waviness_height_nm",
    "waviness_wavelength_nm",
    "waviness_branches",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write WCNTSegNET summary results into the DB.")
    parser.add_argument("--db-path", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--summary-path", type=Path, default=DEFAULT_SUMMARY_PATH)
    parser.add_argument("--backup-dir", type=Path, default=None)
    return parser.parse_args()


def load_summary(summary_path: Path) -> dict[str, Any]:
    return json.loads(summary_path.read_text(encoding="utf-8"))


def export_backup(conn: sqlite3.Connection, image_ids: list[int], backup_path: Path) -> int:
    placeholders = ",".join("?" for _ in image_ids)
    query = f"""
        SELECT {", ".join(BACKUP_COLUMNS)}
        FROM images
        WHERE id IN ({placeholders})
        ORDER BY id
    """
    rows = conn.execute(query, image_ids).fetchall()

    with backup_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(BACKUP_COLUMNS)
        writer.writerows(rows)

    return len(rows)


def build_distribution_json(stats: dict[str, Any]) -> str:
    payload = {
        "representative_nm": stats.get("representative_nm"),
        "mean_nm": stats.get("mean_nm"),
        "median_nm": stats.get("median_nm"),
        "p10_nm": stats.get("p10_nm"),
        "p90_nm": stats.get("p90_nm"),
    }
    return json.dumps(payload, ensure_ascii=False)


def update_rows(conn: sqlite3.Connection, items: list[dict[str, Any]]) -> int:
    updated = 0
    for item in items:
        image_id = item["image_id"]
        features = item.get("wcntsegnet_features", {}) or {}
        diameter_stats = item.get("wcntsegnet_diameter_stats", {}) or {}

        diameter = diameter_stats.get("representative_nm")
        density = features.get("density")
        alignment = features.get("alignment")
        curvature = features.get("curvature_nm")
        tortuosity = features.get("tortuosity")
        diameter_mean = diameter_stats.get("mean_nm")
        diameter_p50 = diameter_stats.get("median_nm")
        diameter_distribution = build_distribution_json(diameter_stats)
        waviness_ratio = features.get("waviness_ratio")
        waviness_height_nm = features.get("waviness_height_nm")
        waviness_wavelength_nm = features.get("waviness_wavelength_nm")
        waviness_branches = features.get("waviness_branches")

        cursor = conn.execute(
            """
            UPDATE images
            SET diameter = ?,
                density = ?,
                alignment = ?,
                curvature = ?,
                processed = 1,
                tortuosity = ?,
                diameter_mean = ?,
                diameter_std = NULL,
                diameter_min = NULL,
                diameter_max = NULL,
                diameter_p25 = NULL,
                diameter_p50 = ?,
                diameter_p75 = NULL,
                diameter_distribution = ?,
                waviness_ratio = ?,
                waviness_height_nm = ?,
                waviness_wavelength_nm = ?,
                waviness_branches = ?
            WHERE id = ?
            """,
            (
                diameter,
                density,
                alignment,
                curvature,
                tortuosity,
                diameter_mean,
                diameter_p50,
                diameter_distribution,
                waviness_ratio,
                waviness_height_nm,
                waviness_wavelength_nm,
                waviness_branches,
                image_id,
            ),
        )
        updated += cursor.rowcount

    return updated


def main() -> None:
    args = parse_args()
    summary = load_summary(args.summary_path)
    items = [item for item in summary.get("items", []) if item.get("status") == "success"]
    image_ids = [int(item["image_id"]) for item in items]

    if not image_ids:
        raise SystemExit("No successful items found in summary.")

    backup_dir = args.backup_dir or args.summary_path.parent
    backup_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = backup_dir / f"wcntsegnet_db_backup_before_write_{timestamp}.csv"

    with sqlite3.connect(args.db_path) as conn:
        backup_count = export_backup(conn, image_ids, backup_path)
        before_changes = conn.total_changes
        updated_count = update_rows(conn, items)
        total_changed_rows = conn.total_changes - before_changes
        conn.commit()

        verify_placeholders = ",".join("?" for _ in image_ids)
        verified = conn.execute(
            f"""
            SELECT COUNT(*)
            FROM images
            WHERE id IN ({verify_placeholders})
              AND processed = 1
              AND density IS NOT NULL
              AND alignment IS NOT NULL
              AND curvature IS NOT NULL
            """,
            image_ids,
        ).fetchone()[0]

    print(f"SUMMARY_PATH={args.summary_path}")
    print(f"DB_PATH={args.db_path}")
    print(f"TARGET_COUNT={len(image_ids)}")
    print(f"BACKUP_PATH={backup_path}")
    print(f"BACKUP_COUNT={backup_count}")
    print(f"UPDATED_COUNT={updated_count}")
    print(f"TOTAL_CHANGED_ROWS={total_changed_rows}")
    print(f"VERIFIED_NON_NULL_COUNT={verified}")


if __name__ == "__main__":
    main()
